"""'Init'

Revision ID: aed5c60b0757
Revises: cddbc8b163cd
Create Date: 2023-04-03 20:21:48.695064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed5c60b0757'
down_revision = 'cddbc8b163cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
