"""add role

Revision ID: f0015925231b
Revises: abfa4fab8941
Create Date: 2023-04-14 17:52:34.220404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0015925231b'
down_revision = 'abfa4fab8941'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
