"""'Init'

Revision ID: 5b0763144e1a
Revises: c9fe31ddfc4f
Create Date: 2023-02-20 12:12:53.678125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0763144e1a'
down_revision = 'c9fe31ddfc4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
