"""'Init'

Revision ID: c9fe31ddfc4f
Revises: 924ee7eeb38e
Create Date: 2023-02-20 09:49:28.647711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fe31ddfc4f'
down_revision = '924ee7eeb38e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
