"""'Init'

Revision ID: 3237fbcf82f2
Revises: 9eb91d9eb253
Create Date: 2023-04-01 19:50:56.473412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3237fbcf82f2'
down_revision = '9eb91d9eb253'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
