"""'Init'

Revision ID: 345863a8e6aa
Revises: aed5c60b0757
Create Date: 2023-04-04 10:30:06.987226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345863a8e6aa'
down_revision = 'aed5c60b0757'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
