"""'Init'

Revision ID: 652139b805c1
Revises: e7654fda7dff
Create Date: 2023-04-02 12:15:48.885107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652139b805c1'
down_revision = 'e7654fda7dff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
